In [1]:
import numpy as np
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
'''Cast a list into a numpy array. This will be a single dimensional array'''
arr = np.array(my_list)

In [3]:
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
matt = np.array(my_mat)
matt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [8]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [11]:
# 5 rows and 3 columns
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# give 20 evenly spaced points between 0-5
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [14]:
0.52631579 - 0.26315789

0.26315789999999994

In [15]:
0.78947368 - 0.52631579

0.26315789

In [16]:
#identity matrix - important concept in linear algebra.
#it is a square matrix where diagonals are 1 and the rest of the elements are 0s.
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [19]:
# create an array of random numbers
np.random.rand(6)

array([0.60314866, 0.23403086, 0.37347763, 0.53501436, 0.09772741,
       0.3760737 ])

In [20]:
#This will give you a random sample of uniform distribution of 5 numbers between 0 to 1
#one dimensional array
arr1 = np.random.rand(5)
print(arr1)
print("*****")
#two dimensional array
arr2 = np.random.rand(3,4)
print(arr2)

[0.72788587 0.22889834 0.41803708 0.05834833 0.09959124]
*****
[[0.67036537 0.67899866 0.7552818  0.01537085]
 [0.02038603 0.11436086 0.97824885 0.60952101]
 [0.12090586 0.10555215 0.5387044  0.45781439]]


In [21]:
#get standard normal distribution numbers
#if we print these numbers, we get a standard normal distribution or Gaussian distribution
arr3 = np.random.randn(5)
print(arr3)

[-0.88439873 -0.74858886  0.40484815 -0.34985685  0.94458515]


In [22]:
#two dimensional array of standard normal distribution
arr4 = np.random.randn(4,4)
print(arr4)

[[-0.8245221   0.35544544 -1.30566738  1.69089421]
 [-0.53879263  1.67911418  1.76210813  1.38893074]
 [-0.08165466  0.03565759 -3.44966214  1.54790857]
 [-1.16985495 -0.61386352 -0.45245829  0.66365104]]


In [23]:
#get a random number between low - high. Low is inclusive and high is exclusive
arr5 = np.random.randint(6,7)
print(arr5)
#if you want to get 10 random integers between a given range, pass a third argument
arr6 = np.random.randint(1,100,20)
print(arr6)

6
[77 88 16 85 67 28 37 20 88 61 43 94 92 19 33 75 27 91 99 93]


In [24]:
arr6 = np.random.randint(1,100,25)
print(arr6)
maxval=arr6.max()
print(maxval)
minval=arr6.min()
print(minval)

[24 61 94 47 73 82 81 83 34  9 43 77 66 86 77 32 82 25 26 20  7 17 50 79
 32]
94
7


In [25]:
#get index location of max value
arr6.argmax()

2

In [26]:
arr6.argmin()

20

In [27]:
#get the shape of an array
arr6.shape

(25,)

In [28]:
#reshape the array
arr6.reshape(5,5)

array([[24, 61, 94, 47, 73],
       [82, 81, 83, 34,  9],
       [43, 77, 66, 86, 77],
       [32, 82, 25, 26, 20],
       [ 7, 17, 50, 79, 32]])

In [29]:
arr6.shape

(25,)

In [30]:
#return the datatype of an array
arr6.dtype

dtype('int64')

In [31]:
#how to select elements or groups of elements from a numpy array
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
#picking up an element from a python array looks a lot like indexing a list.
#use brackets and a slice notation.
arr[3]

3

In [33]:
#slice notation - similar to lists
#it will start at index 1 and stop at index 4
arr[1:5]

array([1, 2, 3, 4])

In [34]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [35]:
#if you want everything upto index 5
arr[:5]

array([0, 1, 2, 3, 4])

In [36]:
#if you want everything starting from a certain index upto the end of the array
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
#numpy arrays can broadcast values
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
#if you take a slice of array, it creates a reference to the original array
slice_of_arr=arr1[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [40]:
slice_of_arr[0:5]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [41]:
arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
#bottom line - it changes the original array. slice of an array is a reference to original array.
#if you want to create a copy of an original array, you need to create a method to copy original array
arr_copy = arr1.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [43]:
arr_copy[0:5]=0
arr_copy

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [44]:
arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [45]:
#two dimensional array
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [46]:
#2-d array indexing
#double bracket notation
arr_2d[0][0]

10

In [47]:
arr_2d[0]

array([10, 20, 30])

In [48]:
arr_2d[1][1]

50

In [49]:
arr_2d[2][1]

80

In [50]:
#single bracket notation
arr_2d[2,1]

80

In [51]:
#how to grab a slice of a 2-d array
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [52]:
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [55]:
arr_2d[:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [57]:
arr_2d[:3,0:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

In [60]:
arr_2d[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [70]:
#conditional selection
arr1 = np.arange(1,11)

In [71]:
bool_arr = arr1 > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [72]:
arr1[bool_arr]

array([ 6,  7,  8,  9, 10])

In [73]:
arr1[arr1>5]

array([ 6,  7,  8,  9, 10])

In [74]:
arr1[arr1<5]

array([1, 2, 3, 4])

In [78]:
arr_2d1 = np.arange(50).reshape(5,10)
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr_2d1[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [83]:
arr_2d1[4:,9:]

array([[49]])

In [85]:
#numpy basic operations
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
#array with array - if you want to add two arrays together
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [89]:
#array with scalar
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [90]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [91]:
arr / arr # 0/0 will show you a warning and a Nan value. code will continue to run

/Users/self/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
1/arr

/Users/self/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [93]:
#do exponent functions
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])